# Generated by Django 5.2 on 2025-04-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cognome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Editore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragione_sociale", models.CharField(max_length=255)),
                ("indirizzo", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                ("anno_edizione", models.IntegerField(blank=True, null=True)),
                (
                    "autore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.autore"
                    ),
                ),
                (
                    "editore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.editore"
                    ),
                ),
            ],
            options={
                "unique_together": {("titolo", "editore", "autore")},
            },
        ),
    ]
