# Generated by Django 5.2 on 2025-04-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('titolo', 'editore', 'autore')},
        ),
    ]
